## This configuration was generated by terraform-provider-oci

resource oci_integration_integration_instance export_poc1 {
  compartment_id    = var.compartment_ocid
  consumption_model = "UCM"
  defined_tags = {
    "as_sandbox.Object" = "Tier1"
    "as_sandbox.Type"   = "user"
    "as_sandbox.User"   = "oracleidentitycloudservice/adam.szynkowski@oracle.com at 2022-04-26T02:02:53.892Z"
    "global.owner"      = "oracleidentitycloudservice/adam.szynkowski@oracle.com"
  }
  display_name = "poc2"
  freeform_tags = {
  }
  idcs_at =  var.jwt
  integration_instance_type = "ENTERPRISE"
  is_byol                   = "true"
  is_file_server_enabled    = "false"
  is_visual_builder_enabled = "false"
  message_packs             = "1"
  /*network_endpoint_details {
    allowlisted_http_ips = [
    ]
    allowlisted_http_vcns {
      allowlisted_ips = [
      ]
      id = "ocid1.vcn.oc1.ap-sydney-1.amaaaaaajdjgirqaimdfeh3fmdv5necekf5dalwbz7q4c6zlqhkxy7qfqwlq"
    }
    is_integration_vcn_allowlisted = "false"
    network_endpoint_type          = "PUBLIC"
  }*/
  state = "ACTIVE"
}

